### ISSUE TITLE
Play a Lure Button has no function.

### ISSUE THREAD

**Issue by Mi605** [marin-m/SongRec#170]
**Issue description:**
The button _Play a Shazam lure_ doesn't play anything. Songrec doesn't crash from this, you can press the button another time (again without producing any result), again and again. All other programs play (or record) audio fine using the running pipewire audio server, even parallel. Console output below.

Songrec was installed by using the line
```
$ cargo install songrec --no-default-features -F gui,ffmpeg,pulse,mpris
```

```
$ songrec --version
SongRec 0.4.2
```

```
$ RUST_BACKTRACE=full songrec gui-norecording

ALSA lib pcm_dmix.c:999:(snd_pcm_dmix_open) unable to open slave
thread '<unnamed>' panicked at /home/Robin/.cargo/registry/src/index.crates.io-6f17d22bba15001f/songrec-0.4.2/src/gui/main_window.rs:655:76:
called `Result::unwrap()` on an `Err` value: NoDevice
stack backtrace:
   0:     0x5582cef9c622 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hffecb437d922f988
   1:     0x5582cefca08c - core::fmt::write::hd9a8d7d029f9ea1a
   2:     0x5582cef993af - std::io::Write::write_fmt::h0e1226b2b8d973fe
   3:     0x5582cef9c3f4 - std::sys_common::backtrace::print::he907f6ad7eee41cb
   4:     0x5582cef9dd7b - std::panicking::default_hook::{{closure}}::h3926193b61c9ca9b
   5:     0x5582cef9dad3 - std::panicking::default_hook::h25ba2457dea68e65
   6:     0x5582cef9e21d - std::panicking::rust_panic_with_hook::h0ad14d90dcf5224f
   7:     0x5582cef9e0f2 - std::panicking::begin_panic_handler::{{closure}}::h4a1838a06f542647
   8:     0x5582cef9caf6 - std::sys_common::backtrace::__rust_end_short_backtrace::h77cc4dc3567ca904
   9:     0x5582cef9de24 - rust_begin_unwind
  10:     0x5582ceba3c45 - core::panicking::panic_fmt::h940d4fd01a4b4fd1
  11:     0x5582ceba4133 - core::result::unwrap_failed::h5119205a73b72b0d
  12:     0x5582cec1d332 - std::sys_common::backtrace::__rust_begin_short_backtrace::h0079c622c8420a1a
  13:     0x5582cebebb19 - core::ops::function::FnOnce::call_once{{vtable.shim}}::he61f6c81ee90f8df
  14:     0x5582cefa2e35 - std::sys::pal::unix::thread::Thread::new::thread_start::h420dad5cf01a9f35
  15:     0x7fa772bc3134 - <unknown>
  16:     0x7fa772c437dc - <unknown>
  17:                0x0 - <unknown>
ALSA lib pcm_dmix.c:999:(snd_pcm_dmix_open) unable to open slave
thread '<unnamed>' panicked at /home/Robin/.cargo/registry/src/index.crates.io-6f17d22bba15001f/songrec-0.4.2/src/gui/main_window.rs:655:76:
called `Result::unwrap()` on an `Err` value: NoDevice
stack backtrace:
   0:     0x5582cef9c622 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hffecb437d922f988
   1:     0x5582cefca08c - core::fmt::write::hd9a8d7d029f9ea1a
   2:     0x5582cef993af - std::io::Write::write_fmt::h0e1226b2b8d973fe
   3:     0x5582cef9c3f4 - std::sys_common::backtrace::print::he907f6ad7eee41cb
   4:     0x5582cef9dd7b - std::panicking::default_hook::{{closure}}::h3926193b61c9ca9b
   5:     0x5582cef9dad3 - std::panicking::default_hook::h25ba2457dea68e65
   6:     0x5582cef9e21d - std::panicking::rust_panic_with_hook::h0ad14d90dcf5224f
   7:     0x5582cef9e0f2 - std::panicking::begin_panic_handler::{{closure}}::h4a1838a06f542647
   8:     0x5582cef9caf6 - std::sys_common::backtrace::__rust_end_short_backtrace::h77cc4dc3567ca904
   9:     0x5582cef9de24 - rust_begin_unwind
  10:     0x5582ceba3c45 - core::panicking::panic_fmt::h940d4fd01a4b4fd1
  11:     0x5582ceba4133 - core::result::unwrap_failed::h5119205a73b72b0d
  12:     0x5582cec1d332 - std::sys_common::backtrace::__rust_begin_short_backtrace::h0079c622c8420a1a
  13:     0x5582cebebb19 - core::ops::function::FnOnce::call_once{{vtable.shim}}::he61f6c81ee90f8df
  14:     0x5582cefa2e35 - std::sys::pal::unix::thread::Thread::new::thread_start::h420dad5cf01a9f35
  15:     0x7fa772bc3134 - <unknown>
  16:     0x7fa772c437dc - <unknown>
  17:                0x0 - <unknown>
```

```
$ wpctl status
PipeWire 'pipewire-0' [1.0.3, Robin@birke, cookie:2515171525]
 └─ Clients:
        32. pipewire                            [1.0.3, Robin@birke, pid:1636441]
        34. WirePlumber                         [1.0.3, Robin@birke, pid:1636439]
        35. WirePlumber [export]                [1.0.3, Robin@birke, pid:1636439]
        43. PipeWire ALSA [volumeicon]          [1.0.3, Robin@birke, pid:1636479]
        52. MainConn                            [1.0.3, Robin@birke, pid:2038280]
        57. Firefox                             [1.0.3, Robin@birke, pid:1956231]
        90. FluidSynth                          [1.0.3, Robin@birke, pid:1970103]
       101. qpwgraph                            [1.0.3, Robin@birke, pid:2035894]
       112. FluidSynth                          [1.0.3, Robin@birke, pid:1969840]
       135. mpv                                 [1.0.3, Robin@birke, pid:2132399]
       143. wpctl                               [1.0.3, Robin@birke, pid:2139129]

Audio
 ├─ Devices:
 │      42. Cedar HDMI Audio [Radeon HD 5400/6300/7300 Series] [alsa]
 │      48. Internes Audio                      [alsa]
 │  
 ├─ Sinks:
 │      47. Cedar HDMI Audio [Radeon HD 5400/6300/7300 Series] Digital Stereo (HDMI) [vol: 1.00]
 │  *   81. Internes Audio Pro                  [vol: 0.85]
 │     141. Internes Audio Pro 1                [vol: 1.00]
 │  
 ├─ Sink endpoints:
 │  
 ├─ Sources:
 │  *  109. Internes Audio Pro                  [vol: 1.00]
 │  
 ├─ Source endpoints:
 │  
 └─ Streams:
        98. FluidSynth                                                  
             95. output_FR       > VT1708S Analog:playback_AUX1	[active]
             97. output_FL       > VT1708S Analog:playback_AUX0	[active]
       104. FluidSynth                                                  
            103. output_FL       > VT1708S Analog:playback_AUX0	[active]
            111. output_FR       > VT1708S Analog:playback_AUX1	[active]
       133. mpv                                                         
             88. output_FL       > VT1708S Analog:playback_AUX0	[active]
            190. output_FR       > VT1708S Analog:playback_AUX1	[active]

Video
 ├─ Devices:
 │  
 ├─ Sinks:
 │  
 ├─ Sink endpoints:
 │  
 ├─ Sources:
 │  
 ├─ Source endpoints:
 │  
 └─ Streams:

Settings
 └─ Default Configured Node Names:

```

**System information:**

OS:
antiX 23.1 full runit 64 bit

```
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Debian
Description:	Debian GNU/Linux 12 (bookworm)
Release:	12
Codename:	bookworm

```

Kernel:
```
$ uname -a
Linux birke 6.5.0-0.deb12.4-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.5.10-1~bpo12+1 (2023-11-23) x86_64 GNU/Linux
```

**Comment by marin-m** [comment]
Thank you for reporting, it was inoperative now and so has been pruned from the last release
